name: Build and Release TylerType

on:
  push:
    tags:
      - 'v*'  # Triggers the workflow when a new version tag (e.g., v1.0.0) is pushed

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build Windows Executable
        if: matrix.os == 'windows-latest'
        run: pyinstaller --onefile --windowed --name TylerType key_counter.py

      - name: Build macOS App
        if: matrix.os == 'macos-latest'
        run: pyinstaller --onefile --windowed --name TylerType key_counter.py

      - name: Upload Windows Build Artifact
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: TylerType-Windows
          path: dist/TylerType.exe

      - name: Upload macOS Build Artifact
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v4
        with:
          name: TylerType-macOS
          path: dist/TylerType.app

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Windows Artifact
        uses: actions/download-artifact@v4
        with:
          name: TylerType-Windows
          path: TylerType-Windows

      - name: Download macOS Artifact
        uses: actions/download-artifact@v4
        with:
          name: TylerType-macOS
          path: TylerType-macOS

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            TylerType-Windows/TylerType.exe
            TylerType-macOS/TylerType.app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}